services:
  audio-ai:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - TRANSCRIPTION_PROVIDER=${TRANSCRIPTION_PROVIDER:-docker_whisper}
      - WHISPER_SERVICE_URL=${WHISPER_SERVICE_URL:-http://localhost:8001}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./processed:/usr/src/app/processed
    restart: unless-stopped

  # Development service (optional)
  app-dev:
    build:
      context: .
      target: development
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - ./processed:/usr/src/app/processed
    environment:
      - TRANSCRIPTION_PROVIDER=${TRANSCRIPTION_PROVIDER:-docker_whisper}
      - WHISPER_SERVICE_URL=${WHISPER_SERVICE_URL:-http://localhost:8001}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: npm run dev