version: '3.8'

services:
  whisper-service:
    build:
      context: .
      dockerfile: whisper.Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    volumes:
      - /tmp:/tmp  # For temporary files
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  audio-ai:
    build: .
    ports:
      - "3000:3000"
    environment:
      - TRANSCRIPTION_PROVIDER=docker_whisper
      - WHISPER_SERVICE_URL=http://whisper-service:8001
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./saved_ideas:/usr/src/app/saved_ideas
    depends_on:
      whisper-service:
        condition: service_healthy
    restart: unless-stopped