services:
  audio-ai:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    volumes:
      # Mount external directory for persistent idea storage
      - ./processed:/usr/src/app/processed
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped

  # Development service (optional)
  app-dev:
    build:
      context: .
      target: development
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - ./processed:/usr/src/app/processed
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: npm run dev
