services:
  whisper-service:
    build:
      context: .
      dockerfile: whisper.Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
    volumes:
      - /tmp:/tmp  # For temporary files
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  audio-ai:
    build: .
    ports:
      - "3000:3000"
    environment:
      - TRANSCRIPTION_PROVIDER=docker_whisper
      - WHISPER_SERVICE_URL=http://whisper-service:8001
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./processed:/usr/src/app/processed
    depends_on:
      whisper-service:
        condition: service_healthy
    restart: unless-stopped